flags: {}
extra-package-dbs: []
packages:
# - perst-plugin
- grec
- perst
- perst-sqlite
- perst-test-data
- perst-servant
- gtree
# - advita
extra-deps:
# - Cabal-2.0.0.2
# - process-1.6.1.0
# - cabal-helper-0.7.3.0
# - dotgen-0.4.2

# resolver: lts-8.7
# resolver: nightly-2017-10-23 # ghc-8.2.1
resolver: nightly-2017-11-29 # ghc-8.2.2
