flags: {}
extra-package-dbs: []
packages:
- bstt
- perst
- perst-sqlite
extra-deps:
  - haddock-api-2.17.3
# - bookkeeper-0.2.4
# - type-level-sets-0.8.0.0
# - type-level-bst-0.1
resolver: nightly-2017-02-03
